import {useEffect,useRef,useState} from "react";
import {X} from "lucide-react";
import {api} from "./api";
type Settings={mode:string;hands:string;countIn:number;metronome:boolean;latency:number;adaptive:boolean;tracks:{track_id:number;mode:string}[]};
type Review={proof:string;contentId:string;book:string;measure:number;page:number;measures:number;start:number;end:number;name:string;speed:number;rounds:number;settings:Settings};
type Draft={start:number;end:number;name:string;notes:string;speed:number;rounds:number};
const modes:Record<string,string>={wait:"等音",flow:"连续",listen:"聆听",recital:"完整演奏",memory:"背谱"};
export function PaperPracticeBuilder({contentId,book,measure,close}:{contentId:string;book:string;measure:number;close:()=>void}){
 const key=`neothesia-paper-practice-draft:${contentId}:${book}:${measure}`;
 const [review,setReview]=useState<Review|null>(null),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState<{id:string;existing:boolean}|null>(null);
 const root=useRef<HTMLElement>(null),prior=useRef(document.activeElement),live=useRef(true),epoch=useRef(0),busyRef=useRef(false),closeRef=useRef(close);closeRef.current=close;busyRef.current=busy;
 const read=async(initial=false)=>{
  const token=++epoch.current;setBusy(true);setError("");
  try{const v=await api.command<Review>({type:"previewPaperPractice",content_id:contentId,book,measure});if(!live.current||token!==epoch.current)return;setReview(v);
   if(initial){let restored:Draft|null=null;try{const r=JSON.parse(localStorage.getItem(key)||"null");if(r&&typeof r.name==="string"&&r.name.length<=80&&typeof r.notes==="string"&&r.notes.length<=8192&&[r.start,r.end,r.speed,r.rounds].every(Number.isFinite))restored=r;}catch{}setDraft(restored??{start:v.start,end:v.end,name:v.name,notes:"",speed:v.speed,rounds:v.rounds});}
  }catch(e){if(live.current&&token===epoch.current){setError(String(e));setReview(null);}}finally{if(live.current&&token===epoch.current)setBusy(false);}
 };
 useEffect(()=>{live.current=true;void read(true);return()=>{live.current=false;epoch.current++;if(prior.current instanceof HTMLElement&&prior.current.isConnected)prior.current.focus();};},[]);
 useEffect(()=>{if(!draft||saved)return;try{localStorage.setItem(key,JSON.stringify(draft));}catch{setError("本机无法保留草稿，请保存练习段后再关闭。");}},[draft,saved,key]);
 useEffect(()=>{const keydown=(e:KeyboardEvent)=>{if(e.key==="Escape"){e.preventDefault();e.stopImmediatePropagation();if(!busyRef.current)closeRef.current();}else if(e.key==="Tab"){const nodes=[...(root.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea:not(:disabled)')??[])].filter(n=>n.getClientRects().length>0),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};window.addEventListener("keydown",keydown,true);return()=>window.removeEventListener("keydown",keydown,true);},[]);
 const update=(patch:Partial<Draft>)=>{if(draft)setDraft({...draft,...patch});};
 const valid=!!review&&!!draft&&!!draft.name.trim()&&draft.name.length<=80&&draft.notes.length<=8192&&Number.isInteger(draft.start)&&Number.isInteger(draft.end)&&draft.start>=1&&draft.start<=measure&&draft.end>=measure&&draft.end<=review.measures&&draft.speed>=.25&&draft.speed<=2&&Number.isInteger(draft.rounds)&&draft.rounds>=1&&draft.rounds<=99;
 const save=async()=>{if(!valid||!review||!draft)return;setBusy(true);setError("");try{const v=await api.command<{id:string;existing:boolean}>({type:"savePaperPractice",request:{contentId,book,measure,proof:review.proof,...draft}});if(live.current){setSaved(v);try{localStorage.removeItem(key);}catch{}}}catch(e){if(live.current)setError(String(e));}finally{if(live.current)setBusy(false);}};
 const open=async()=>{if(!saved)return;setBusy(true);setError("");try{await api.command({type:"openPassage",id:saved.id});closeRef.current();}catch(e){if(live.current)setError(`练习段已保存，打开失败：${String(e)}`);}finally{if(live.current)setBusy(false);}};
 return <div className="modal-backdrop"><section ref={root} className="settings-dialog paper-practice-dialog" role="dialog" aria-modal="true" aria-labelledby="paper-practice-title"><div className="dialog-heading"><div><h2 id="paper-practice-title">从纸谱建立练习段</h2><p>第 {review?.page??"—"} 页 · 第 {measure} 演奏小节</p></div><button autoFocus disabled={busy} aria-label="关闭纸谱练习段" onClick={close}><X size={18}/></button></div>
 {error&&<p role="alert" className="dialog-error">{error}</p>}
 {review&&<p className="paper-practice-conditions">沿用当前{modes[review.settings.mode]??review.settings.mode}模式、{({both:"双手",left:"左手",right:"右手"} as Record<string,string>)[review.settings.hands]??review.settings.hands}、预备 {review.settings.countIn} 小节、{review.settings.metronome?"开":"关"}节拍器、输入补偿 {review.settings.latency} 毫秒{review.settings.adaptive?"、自动调速":""}。声部设置和已保存指法继续使用。</p>}
 {review&&<div className="paper-practice-tracks">{review.settings.tracks.map(t=><span key={t.track_id}>音轨 {t.track_id+1} · {({Human:"自己弹",Auto:"伴奏",Mute:"静音",human:"自己弹",auto:"伴奏",mute:"静音"} as Record<string,string>)[t.mode]??t.mode}</span>)}</div>}
 {draft&&<fieldset disabled={busy||!!saved} className="paper-practice-fields"><label>名称<input aria-label="纸谱练习段名称" maxLength={80} value={draft.name} onChange={e=>update({name:e.target.value})}/></label><div className="paper-practice-range"><label>起始小节<input aria-label="纸谱练习起始小节" type="number" min={1} max={measure} value={draft.start} onChange={e=>update({start:Number(e.target.value)})}/></label><label>结束小节<input aria-label="纸谱练习结束小节" type="number" min={measure} max={review?.measures} value={draft.end} onChange={e=>update({end:Number(e.target.value)})}/></label><label>速度 %<input aria-label="纸谱练习速度" type="number" min={25} max={200} value={Math.round(draft.speed*100)} onChange={e=>update({speed:Number(e.target.value)/100})}/></label><label>重复遍数<input aria-label="纸谱练习遍数" type="number" min={1} max={99} value={draft.rounds} onChange={e=>update({rounds:Number(e.target.value)})}/></label></div><label>练习要求<textarea aria-label="纸谱练习要求" rows={3} maxLength={4000} value={draft.notes} onChange={e=>update({notes:e.target.value})}/></label><p>范围须包含第 {measure} 演奏小节。保存后可从“练习段落”继续修改、打开，或加入练习计划。未保存草稿保留在本机。</p></fieldset>}
 {saved&&<p role="status">{saved.existing?"此练习段已经保存，已找到原段落。":"已保存练习段。"}打开后会按所选速度与遍数设置循环。</p>}
 <div className="dialog-actions">{!saved&&<><button disabled={busy} onClick={()=>void read()}>重新核对条件</button><button className="primary" disabled={busy||!valid} onClick={()=>void save()}>{busy?"正在处理…":"保存练习段"}</button></>}{saved&&<button className="primary" disabled={busy} onClick={()=>void open()}>打开练习段</button>}<button disabled={busy} onClick={close}>{saved?"完成":"保留草稿并关闭"}</button></div></section></div>;
}
