import { test, expect } from "@playwright/test";

test("同手跨音轨持音推荐、身份保护、联合预览与仅保存所选音轨", async({page,request})=>{
  const raw=(data:unknown)=>request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});
  const command=async(data:unknown)=>{const r=await raw(data);expect(r.ok(),await r.text()).toBeTruthy();return r.json();};
  const read=async()=> (await request.get("http://127.0.0.1:32124/api/song")).json();
  const attrs=`<attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes>`;
  const xml=`<score-partwise version="4.0"><work><work-title>同手分轨持音</work-title></work><part-list><score-part id="P1"><part-name>旋律</part-name></score-part><score-part id="P2"><part-name>持音声部</part-name></score-part></part-list><part id="P1"><measure number="1">${attrs}${["E","F"].map(p=>`<note><pitch><step>${p}</step><octave>4</octave></pitch><duration>1</duration><type>quarter</type></note>`).join("")}<note><rest/><duration>2</duration><type>half</type></note></measure></part><part id="P2"><measure number="1">${attrs}<note><pitch><step>C</step><octave>4</octave></pitch><duration>4</duration><type>whole</type></note></measure></part></score-partwise>`;
  await command({type:"importScore",bytes:Array.from(Buffer.from(xml)),name:"同手分轨.musicxml",default_bpm:120});
  const song=await read();const melody=song.notes.find((n:any)=>n.pitch===64),bass=song.notes.find((n:any)=>n.pitch===60);
  expect(melody.track).not.toBe(bass.track);
  for(const id of [melody.track,bass.track])await command({type:"track",id,mode:"human",part:"right",visible:true});
  await command({type:"editFingersFor",content_id:song.contentId,edits:[{track_id:bass.track,note_index:bass.index,finger:1}]});
  const req={content_id:song.contentId,track:melody.track,index:melody.index,hand:"RightHand",profile:"Standard",range:[1,1],keep_saved:false,pins:[]};
  const generated=await command({type:"suggestFingerPlans",request:req});
  expect(generated.contextTracks).toEqual([bass.track]);
  expect(generated.plans[0].proposals).toHaveLength(2);
  expect(generated.plans.every((p:any)=>p.proposals.every((n:any)=>n.track===melody.track && n.finger>1))).toBeTruthy();
  const first=generated.context.findIndex((n:any)=>n.track===bass.track && n.index===bass.index);
  expect(generated.plans[0].contextFingers[first]).toBe(1);
  const edit=[{track_id:melody.track,note_index:melody.index,finger:1}];
  const review=await command({type:"reviewFingerAcceptance",request:req,fingerprint:generated.fingerprint,edits:edit});
  expect(review.valid).toBeFalsy();expect(review.conflicts[0].fromTrack).toBe(bass.track);
  const rejected=await raw({type:"acceptFingerPlan",request:req,fingerprint:generated.fingerprint,edits:edit});expect(rejected.ok()).toBeFalsy();
  const outsider=await raw({type:"reviewFingerAcceptance",request:req,fingerprint:generated.fingerprint,edits:[{track_id:bass.track,note_index:bass.index,finger:2}]});expect(outsider.ok()).toBeFalsy();
  await command({type:"editFingersFor",content_id:song.contentId,edits:[{track_id:bass.track,note_index:bass.index,finger:2}]});
  const stale=await raw({type:"acceptFingerPlan",request:req,fingerprint:generated.fingerprint,edits:generated.plans[0].proposals.map((p:any)=>({track_id:p.track,note_index:p.index,finger:p.finger}))});expect(stale.ok()).toBeFalsy();expect(await stale.text()).toContain("已变化");
  await command({type:"editFingersFor",content_id:song.contentId,edits:[{track_id:bass.track,note_index:bass.index,finger:1}]});
  await page.goto("/");await expect(page.getByText("本地引擎已连接",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"指法建议",exact:true}).click();
  const d=page.getByRole("dialog",{name:"指法建议"});
  await d.getByLabel("指法音轨").selectOption(String(melody.track));
  await d.getByLabel("指法起始小节").fill("1");await d.getByLabel("指法结束小节").fill("1");
  await d.getByRole("button",{name:"生成建议",exact:true}).click();
  await expect(d.getByText(/联合参考同一只手的音轨/)).toBeVisible();
  await expect(d.getByText(/联合参考同一只手的音轨/)).toContainText(`本次只保存 ${song.tracks.find((t:any)=>t.id===melody.track).name} 的勾选建议`);
  await expect(d.getByText(/联合参考同一只手的音轨/)).toContainText(song.tracks.find((t:any)=>t.id===bass.track).name);
  await expect(d.locator("tbody tr")).toHaveCount(2);
  await d.getByRole("group",{name:"手位预览内容"}).getByRole("button",{name:"保存后的实际指法",exact:true}).click();
  await expect(d.locator("svg[aria-label='当前和弦及仍按住的音符指法'] text").first()).toHaveText("1");
  await page.screenshot({path:"../outputs/Neothesia-同手音轨联合指法.png",fullPage:true});
  await page.setViewportSize({width:900,height:800});
  expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBeTruthy();
  await d.getByRole("button",{name:/接受并保存/}).click();await expect(d).toHaveCount(0);
  const saved=await read();expect(saved.notes.find((n:any)=>n.track===bass.track && n.index===bass.index).finger).toBe(1);
  expect(saved.notes.filter((n:any)=>n.track===melody.track).every((n:any)=>n.finger>1)).toBeTruthy();
  await command({type:"editFingersFor",content_id:song.contentId,edits:[{track_id:bass.track,note_index:bass.index,finger:null}]});
  await page.reload();await page.getByRole("button",{name:"指法建议",exact:true}).click();
  await d.getByLabel("指法音轨").selectOption(String(melody.track));await d.getByLabel("指法起始小节").fill("1");await d.getByLabel("指法结束小节").fill("1");
  await d.getByRole("button",{name:"生成建议",exact:true}).click();
  const audit=d.getByRole("region",{name:"指法保存结果审阅"});
  await expect(audit.getByText(/同手其他音轨在本选段还有 1 个未标记位置/)).toBeVisible();
  await expect(d.getByRole("button",{name:/接受并保存/})).toBeDisabled();
  await audit.getByRole("checkbox",{name:"已审阅保留指法和未标记位置，只保存勾选音符"}).check();
  await d.getByRole("button",{name:/接受并保存/}).click();
  expect((await read()).notes.find((n:any)=>n.track===bass.track && n.index===bass.index).finger).toBeNull();
  await command({type:"track",id:bass.track,mode:"human",part:"left",visible:true});
  const otherHand=await command({type:"suggestFingerPlans",request:req});expect(otherHand.contextTracks).toHaveLength(0);
});
