import { test, expect } from "@playwright/test";

test("同手多轨共同编辑、独立固定、逐轨审阅、一笔保存撤销及主轨休止范围", async({page,request})=>{
  const raw=(data:unknown)=>request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});
  const command=async(data:unknown)=>{const r=await raw(data);expect(r.ok(),await r.text()).toBeTruthy();return r.json();};
  const read=async()=> (await request.get("http://127.0.0.1:32124/api/song")).json();
  const attrs=`<attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes>`;
  const note=(p:string,d:number)=>`<note><pitch><step>${p}</step><octave>4</octave></pitch><duration>${d}</duration><type>${d===4?"whole":"quarter"}</type></note>`;
  const xml=`<score-partwise version="4.0"><work><work-title>共同编辑两条右手声部</work-title></work><part-list><score-part id="P1"><part-name>旋律</part-name></score-part><score-part id="P2"><part-name>持音</part-name></score-part></part-list><part id="P1"><measure number="1">${attrs}${note("E",1)}${note("F",1)}<note><rest/><duration>2</duration><type>half</type></note></measure><measure number="2"><note><rest/><duration>4</duration><type>whole</type></note></measure></part><part id="P2"><measure number="1">${attrs}${note("C",4)}</measure><measure number="2">${note("D",4)}</measure></part></score-partwise>`;
  await command({type:"importScore",bytes:Array.from(Buffer.from(xml)),name:"多轨共同编辑.musicxml",default_bpm:120});
  const song=await read(), melody=song.notes.find((n:any)=>n.pitch===64), bass=song.notes.find((n:any)=>n.pitch===60);
  for(const id of [melody.track,bass.track])await command({type:"track",id,mode:"human",part:"right",visible:true});
  await command({type:"editFingersFor",content_id:song.contentId,edits:song.notes.map((n:any)=>({track_id:n.track,note_index:n.index,finger:null}))});
  const req={content_id:song.contentId,track:melody.track,index:melody.index,hand:"RightHand",profile:"Standard",range:[1,2],keep_saved:false,target_tracks:[bass.track],pins:[]};
  const rest=await command({type:"suggestFingerPlans",request:{...req,range:[2,2]}});
  expect(rest.plans[0].proposals).toHaveLength(1);expect(rest.plans[0].proposals[0].track).toBe(bass.track);
  const generated=await command({type:"suggestFingerPlans",request:req});expect(generated.plans[0].proposals).toHaveLength(4);
  const bad=await raw({type:"acceptFingerPlan",request:req,fingerprint:generated.fingerprint,edits:[{track_id:melody.track,note_index:melody.index,finger:3},{track_id:bass.track,note_index:99999,finger:1}]});
  expect(bad.ok()).toBeFalsy();expect((await read()).notes.every((n:any)=>n.finger===null)).toBeTruthy();
  const duplicate=await raw({type:"suggestFingerPlans",request:{...req,target_tracks:[bass.track,bass.track]}});expect(duplicate.ok()).toBeFalsy();
  await page.goto("/");await expect(page.getByText("本地引擎已连接",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"指法建议",exact:true}).click();
  const d=page.getByRole("dialog",{name:"指法建议"}), melodyName=song.tracks.find((t:any)=>t.id===melody.track).name,bassName=song.tracks.find((t:any)=>t.id===bass.track).name;
  await d.getByLabel("指法音轨").selectOption(String(melody.track));
  await d.getByLabel("指法起始小节").fill("1");await d.getByLabel("指法结束小节").fill("2");
  await d.getByRole("checkbox",{name:`共同编辑 ${bassName}`}).check();
  await d.getByText("固定选段内已有指法",{exact:true}).click();
  await d.getByRole("button",{name:"生成建议",exact:true}).click();await expect(d.locator("tbody tr")).toHaveCount(4);
  await d.getByLabel(`${melodyName} · 音符 ${melody.index+1} 建议手指`).selectOption("3");
  await d.getByLabel(`${bassName} · 音符 ${bass.index+1} 建议手指`).selectOption("1");
  await d.getByRole("button",{name:"按修改重新推荐"}).click();
  await expect(d.getByLabel(`${melodyName} · 音符 ${melody.index+1} 建议手指`)).toHaveValue("3");
  await expect(d.getByLabel(`${bassName} · 音符 ${bass.index+1} 建议手指`)).toHaveValue("1");
  const audit=d.getByRole("region",{name:"指法保存结果审阅"});
  await expect(audit.locator(".finger-batch-summary > div")).toHaveCount(2);
  const bassRow=audit.locator(".finger-batch-summary > div").filter({has:page.getByText(bassName,{exact:true})});
  await bassRow.getByRole("button",{name:"取消该轨选择"}).click();
  await expect(audit.getByText(/接受 2 个 · 保留已有 0 个 · 未标记 2 个/)).toBeVisible();
  await expect(d.getByRole("button",{name:/接受并保存/})).toBeDisabled();
  await d.getByRole("group",{name:"手位预览内容"}).getByRole("button",{name:"保存后的实际指法",exact:true}).click();
  await expect(d.locator("svg[aria-label='当前和弦及仍按住的音符指法'] text")).toHaveText(["·","3"]);
  await bassRow.getByRole("button",{name:"接受该轨全部"}).click();
  await expect(d.getByRole("button",{name:/接受并保存/})).toBeEnabled();
  await expect(d.locator(".fingering-table-wrap")).toHaveJSProperty("clientHeight", await d.locator(".fingering-table-wrap").evaluate(el=>el.scrollHeight));
  expect(await d.evaluate(el=>getComputedStyle(el).overflowY)).toBe("auto");
  await audit.scrollIntoViewIfNeeded();
  await page.screenshot({path:"../outputs/Neothesia-多音轨共同指法审阅.png",fullPage:true});
  await page.setViewportSize({width:900,height:800});expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBeTruthy();
  await d.getByRole("button",{name:/接受并保存/}).click();await expect(d).toHaveCount(0);
  const saved=await read();expect(saved.notes.every((n:any)=>n.finger!==null)).toBeTruthy();
  expect(saved.notes.find((n:any)=>n.track===melody.track&&n.index===melody.index).finger).toBe(3);
  expect(saved.notes.find((n:any)=>n.track===bass.track&&n.index===bass.index).finger).toBe(1);
  const profiles=await command({type:"fingerProfiles"});expect(profiles.profilesByHand[`${melody.track}:right`]).toBe("Standard");expect(profiles.profilesByHand[`${bass.track}:right`]).toBe("Standard");
  await command({type:"undoFingersFor",content_id:song.contentId});expect((await read()).notes.every((n:any)=>n.finger===null)).toBeTruthy();
  const fresh=await command({type:"suggestFingerPlans",request:req});
  await command({type:"acceptFingerPlan",request:req,fingerprint:fresh.fingerprint,edits:fresh.plans[0].proposals.map((p:any)=>({track_id:p.track,note_index:p.index,finger:p.finger}))});
  const persisted=await read();await command({type:"load",path:song.sourcePath,title:song.title});
  expect((await read()).notes.map((n:any)=>[n.track,n.index,n.finger])).toEqual(persisted.notes.map((n:any)=>[n.track,n.index,n.finger]));
});
