import { test, expect } from "@playwright/test";

test("局部接受审阅保留指法、阻止冲突、完整接受恢复与撤销", async ({page,request})=>{
  const raw=(data:unknown)=>request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});
  const command=async(data:unknown)=>{const r=await raw(data);expect(r.ok(),await r.text()).toBeTruthy();return r.json();};
  const read=async()=> (await request.get("http://127.0.0.1:32124/api/song")).json();
  const xml=`<score-partwise version="4.0"><work><work-title>局部指法保存审阅</work-title></work><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes><note><pitch><step>C</step><octave>4</octave></pitch><duration>4</duration><type>whole</type></note><note><chord/><pitch><step>E</step><octave>4</octave></pitch><duration>4</duration><type>whole</type></note></measure></part></score-partwise>`;
  await command({type:"importScore",bytes:Array.from(Buffer.from(xml)),name:"局部指法保存.musicxml",default_bpm:120});
  const song=await read(), track=song.notes[0].track;
  const low=song.notes.find((n:any)=>n.pitch===60), high=song.notes.find((n:any)=>n.pitch===64);
  await command({type:"track",id:track,mode:"human",part:"right",visible:true});
  await command({type:"editFingersFor",content_id:song.contentId,edits:[{track_id:track,note_index:low.index,finger:1},{track_id:track,note_index:high.index,finger:3}]});
  const req={content_id:song.contentId,track,index:low.index,hand:"RightHand",profile:"Standard",range:[1,1],keep_saved:false,pins:[{index:low.index,finger:3}]};
  const generated=await command({type:"suggestFingerPlans",request:req});
  const edits=[{track_id:track,note_index:low.index,finger:3}];
  const review=await command({type:"reviewFingerAcceptance",request:req,fingerprint:generated.fingerprint,edits});
  expect(review.valid).toBeFalsy();expect(review.retained).toBe(1);expect(review.conflicts[0].reason).toContain("同一手指");
  const rejected=await raw({type:"acceptFingerPlan",request:req,fingerprint:generated.fingerprint,edits});
  expect(rejected.ok()).toBeFalsy();
  expect((await read()).notes.map((n:any)=>n.finger)).toEqual(song.notes.map((n:any)=>n.pitch===60?1:3));
  await page.goto("/");await expect(page.getByText("本地引擎已连接",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"指法建议",exact:true}).click();
  const d=page.getByRole("dialog",{name:"指法建议"});
  await d.getByLabel("指法起始小节").fill("1");await d.getByLabel("指法结束小节").fill("1");
  await d.getByText("固定选段内已有指法",{exact:true}).click();
  await d.getByRole("button",{name:"生成建议",exact:true}).click();
  await d.getByLabel(`音符 ${low.index+1} 建议手指`).selectOption("3");
  await d.getByRole("button",{name:"按修改重新推荐"}).click();
  await expect(d.getByRole("button",{name:/接受并保存/})).toBeEnabled();
  await d.getByLabel(`接受音符 ${high.index+1} 指法`).uncheck();
  const audit=d.getByRole("region",{name:"指法保存结果审阅"});
  await expect(audit.getByText(/接受 1 个 · 保留已有 1 个 · 未标记 0 个/)).toBeVisible();
  await expect(audit.getByRole("button",{name:/同一手指同时分配给不同音符/})).toBeVisible();
  await expect(d.getByRole("button",{name:/接受并保存/})).toBeDisabled();
  await audit.getByRole("button",{name:/同一手指同时分配给不同音符/}).click();
  await expect(d.getByText(/保存结果手位/)).toBeVisible();
  await expect(d.locator("svg[aria-label='当前和弦及仍按住的音符指法'] text")).toHaveText(["3","3"]);
  await page.screenshot({path:"../outputs/Neothesia-局部指法保存审阅.png",fullPage:true});
  await page.setViewportSize({width:900,height:800});
  expect(await audit.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBeTruthy();
  await d.getByLabel(`接受音符 ${high.index+1} 指法`).check();
  await expect(d.getByRole("button",{name:/接受并保存/})).toBeEnabled();
  await d.getByRole("button",{name:/接受并保存/}).click();await expect(d).toHaveCount(0);
  const saved=await read();expect(saved.notes.find((n:any)=>n.index===low.index).finger).toBe(3);
  expect(saved.notes.find((n:any)=>n.index===high.index).finger).toBeGreaterThan(3);
  await command({type:"undoFingersFor",content_id:song.contentId});
  expect((await read()).notes.map((n:any)=>n.finger)).toEqual(song.notes.map((n:any)=>n.pitch===60?1:3));
  await command({type:"editFingersFor",content_id:song.contentId,edits:[{track_id:track,note_index:high.index,finger:null}]});
  await page.reload();await page.getByRole("button",{name:"指法建议",exact:true}).click();
  await d.getByLabel("指法起始小节").fill("1");await d.getByLabel("指法结束小节").fill("1");
  await d.getByRole("button",{name:"生成建议",exact:true}).click();
  await d.getByLabel(`接受音符 ${high.index+1} 指法`).uncheck();
  await expect(audit.getByText(/接受 1 个 · 保留已有 0 个 · 未标记 1 个/)).toBeVisible();
  await d.getByRole("group",{name:"手位预览内容"}).getByRole("button",{name:"保存后的实际指法",exact:true}).click();
  await expect(d.locator("svg[aria-label='当前和弦及仍按住的音符指法'] text")).toHaveText(["1","·"]);
  await expect(d.getByRole("button",{name:/接受并保存/})).toBeDisabled();
  await audit.getByRole("checkbox",{name:"已审阅保留指法和未标记位置，只保存勾选音符"}).check();
  await d.getByRole("button",{name:/接受并保存/}).click();
  expect((await read()).notes.find((n:any)=>n.index===high.index).finger).toBeNull();
});
