import {test,expect} from "@playwright/test";
test("双手审阅生成练习段、编辑保存与重开",async({page,request})=>{
 const cmd=async(data:unknown)=>{const r=await request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});expect(r.ok(),await r.text()).toBeTruthy();return r.json()};
 await cmd({type:"generate",spec:{tonic:4,tonality:"Major",minor_form:"Natural",pattern:"Scale",direction:"UpAndDown",hands:"Both",octaves:1,repetitions:1,tempo_bpm:120}});
 const before=await cmd({type:"currentSong"});await page.goto("/");await page.getByRole("button",{name:"指法建议",exact:true}).click();await page.getByRole("button",{name:"双手一起审阅",exact:true}).click();const d=page.getByRole("dialog",{name:"双手指法审阅",exact:true});await d.getByLabel("双手终点小节").fill("2");await d.getByRole("button",{name:"生成双手建议",exact:true}).click();await d.getByRole("button",{name:"核对双手保存结果",exact:true}).click();await expect(d.locator(".finger-pair-review")).toContainText("检查通过");
 const title="双手衔接慢练"+Date.now();await d.getByRole("button",{name:/建立双手练习段|整理双手难点练习段/}).click();const builder=d.getByRole("region",{name:"指法难点练习段"});await builder.getByLabel("难点段名称 1",{exact:true}).fill(title);await builder.getByLabel("难点段起始小节 1",{exact:true}).fill("1");await builder.getByLabel("难点段结束小节 1",{exact:true}).fill("1");await builder.getByLabel("难点段速度 1",{exact:true}).fill("55");await builder.getByLabel("难点段重复次数 1",{exact:true}).fill("4");await builder.getByLabel("难点段备注 1",{exact:true}).fill("先稳定双手，再恢复原速");await builder.scrollIntoViewIfNeeded();await page.screenshot({path:"../outputs/Neothesia-双手难点练习段.png"});await page.setViewportSize({width:700,height:900});await builder.scrollIntoViewIfNeeded();await page.screenshot({path:"../outputs/Neothesia-双手难点练习段-窄窗.png"});await page.setViewportSize({width:1440,height:960});await builder.getByRole("button",{name:"保存 1 个双手练习段",exact:true}).click();await expect(builder.getByRole("status")).toContainText("已保存 1 个练习段");
 expect((await cmd({type:"currentSong"})).fingerUndoAvailable).toBe(before.fingerUndoAvailable);const passage=(await cmd({type:"passages"})).passages.find((p:any)=>p.name===title);expect(passage.settings.hands).toBe("both");expect(passage.speed).toBe(.55);expect(passage.settings.rounds).toBe(4);expect(passage.settings.tracks.filter((t:any)=>t.mode==="Human")).toHaveLength(2);
 page.once("dialog",d=>d.accept());await d.getByRole("button",{name:"关闭",exact:true}).click();await page.getByLabel("关闭指法建议").click();await page.getByRole("button",{name:"练习段落",exact:true}).click();const parent=page.getByRole("dialog",{name:"练习段落",exact:true});await parent.locator(".passage-select").filter({hasText:title}).click();await parent.locator("article").filter({hasText:title}).getByRole("button",{name:"练这一段",exact:true}).click();await expect(parent).toHaveCount(0);const state=await (await request.get("http://127.0.0.1:32124/api/state")).json();expect(state.hands).toBe("both");expect(state.speed).toBe(.55);expect(state.rounds).toBe(4);
});
