import { test, expect } from "@playwright/test";

test("难点小节整理、批量失败不写入、重开练习与日课保存", async ({page,request})=>{
  const raw=(data:unknown)=>request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});
  const cmd=async(data:unknown)=>{const r=await raw(data);expect(r.ok(),await r.text()).toBeTruthy();return r.json();};
  const xml=`<score-partwise version="4.0"><work><work-title>难点段练习</work-title></work><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>4</divisions><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes><note><rest/><duration>15</duration></note><note><pitch><step>E</step><octave>4</octave></pitch><duration>1</duration></note></measure><measure number="2"><note><pitch><step>F</step><octave>4</octave></pitch><duration>1</duration></note><note><rest/><duration>15</duration></note></measure></part></score-partwise>`;
  await cmd({type:"importScore",bytes:Array.from(Buffer.from(xml)),name:"难点段练习.musicxml",default_bpm:120});
  const read=async()=> (await request.get("http://127.0.0.1:32124/api/song")).json();
  const song=await read(), notes=[...song.notes].sort((a:any,b:any)=>a.start-b.start), track=notes[0].track;
  await cmd({type:"track",id:track,mode:"human",part:"right",visible:true});
  await cmd({type:"editFingersFor",content_id:song.contentId,edits:notes.map((n:any,i:number)=>({track_id:track,note_index:n.index,finger:[3,1][i]}))});
  const req={content_id:song.contentId,track,index:notes[0].index,hand:"RightHand",profile:"Standard",range:[1,2],keep_saved:true,pins:[],practice_rate:1};
  const plan=await cmd({type:"suggestFingerPlans",request:req});
  expect(plan.plans[0].review[0]).toMatchObject({fromMeasure:1,measure:2,kind:"rapidTurn"});
  const passages=()=>cmd({type:"passages"});const before=(await passages()).passages.length;
  const range={name:"难点",start:1,end:2,notes:"",speed:0.6,rounds:3};
  const bad=await raw({type:"saveFingerPractice",request:req,fingerprint:plan.fingerprint,ranges:[range,{...range,end:9999}]});
  expect(bad.ok()).toBeFalsy();expect((await passages()).passages).toHaveLength(before);
  await page.goto("/");await expect(page.getByText("本地引擎已连接",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"指法建议",exact:true}).click();
  const d=page.getByRole("dialog",{name:"指法建议"});
  await d.getByLabel("指法起始小节").fill("1");await d.getByLabel("指法结束小节").fill("2");
  await d.getByRole("button",{name:"生成建议",exact:true}).click();
  const builder=d.getByRole("region",{name:"指法难点复核"}).getByRole("region",{name:"指法难点练习段"});
  await builder.getByRole("button",{name:"整理为练习段"}).click();
  await expect(builder.getByLabel("难点段起始小节 1")).toHaveValue("1");await expect(builder.getByLabel("难点段结束小节 1")).toHaveValue("2");
  await expect(builder.getByLabel("难点段速度 1")).toHaveValue("62");
  await builder.getByLabel("难点段名称 1").fill("右手跨小节衔接");await builder.getByLabel("难点段速度 1").fill("60");await builder.getByLabel("难点段重复次数 1").fill("4");
  await page.screenshot({path:"../outputs/Neothesia-指法难点练习段.png",fullPage:true});
  await builder.getByRole("button",{name:"保存 1 个难点练习段",exact:true}).click();
  await expect(builder.getByRole("status")).toContainText("已保存 1 个练习段");
  const actual=d.getByRole("region",{name:"指法保存结果审阅"}).getByRole("region",{name:"指法难点练习段"});
  await actual.getByRole("button",{name:"整理为练习段"}).click();
  await expect(actual.getByLabel("难点段起始小节 1")).toHaveValue("1");
  await page.setViewportSize({width:900,height:800});
  expect(await actual.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBeTruthy();
  await actual.getByRole("button",{name:"取消整理"}).click();
  const saved=(await passages()).passages.at(-1);
  expect(saved).toMatchObject({name:"右手跨小节衔接",start:1,end:2,speed:0.6,settings:{rounds:4,hands:"right",mode:"wait"}});
  expect(saved.settings.tracks.find((t:any)=>t.track_id===track).mode).toBe("Human");
  expect((await read()).notes.map((n:any)=>n.finger)).toEqual(song.notes.map((n:any)=>notes.findIndex((o:any)=>o.index===n.index)===0?3:1));
  await cmd({type:"load",path:song.sourcePath,title:song.title});expect((await passages()).passages.at(-1).id).toBe(saved.id);
  await cmd({type:"openPassage",id:saved.id});
  const state=await (await request.get("http://127.0.0.1:32124/api/state")).json();
  expect(state).toMatchObject({hands:"right",speed:0.6,rounds:4,mode:"wait"});
  const routine=await cmd({type:"saveRoutine",id:null,day:null,name:"指法衔接日课",notes:"",copy_of:null});
  const item=await cmd({type:"saveRoutineItem",routine_id:routine.id,day:null,id:null,source:"passage",source_id:saved.id,title:saved.name,notes:saved.notes,
    goal:{passes:2,accuracy:90,onTime:null,consecutive:false,attemptLimit:20}});
  const plans=await cmd({type:"routines",day:"2026-10-02"});
  expect(plans.plans.find((p:any)=>p.id===routine.id).items.find((i:any)=>i.id===item.id)).toMatchObject({speed:0.6,settings:{rounds:4,hands:"right"},target:{kind:"passage",start:1,end:2}});
  const stale=await raw({type:"saveFingerPractice",request:{...req,practice_rate:0.5},fingerprint:plan.fingerprint,ranges:[range]});expect(stale.ok()).toBeFalsy();expect((await passages()).passages).toHaveLength(before+1);
});
