import {test,expect} from "@playwright/test";
test("持音换指示范、后续占用校验与独立片段",async({page,request})=>{
 const raw=(data:unknown)=>request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});
 const cmd=async(data:unknown)=>{const r=await raw(data);expect(r.ok(),await r.text()).toBeTruthy();return r.json();};
 await cmd({type:"stopRoutine"});await cmd({type:"pause"});
 const passage=`<note><pitch><step>C</step><octave>4</octave></pitch><duration>8</duration><voice>1</voice><type>whole</type></note><backup><duration>8</duration></backup><forward><duration>4</duration></forward><note><pitch><step>E</step><octave>4</octave></pitch><duration>2</duration><voice>2</voice><type>quarter</type></note><note><pitch><step>F</step><octave>4</octave></pitch><duration>2</duration><voice>2</voice><type>quarter</type></note>`;
 const xml=`<score-partwise version="4.0"><work><work-title>持音换指示范课堂</work-title></work><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>2</divisions><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes>${passage}</measure><measure number="2"><note><pitch><step>G</step><octave>4</octave></pitch><duration>2</duration><type>quarter</type></note><note><rest/><duration>6</duration><type>half</type></note></measure><measure number="3">${passage}</measure></part></score-partwise>`;
 await cmd({type:"importScore",bytes:[...Buffer.from(xml)],name:"持音换指示范.musicxml",default_bpm:120});
 const song=await cmd({type:"currentSong"}),track=song.notes[0].track,held=song.notes.filter((n:any)=>n.pitch===60).sort((a:any,b:any)=>a.start-b.start),gap=song.notes.find((n:any)=>n.pitch===67),later=song.notes.find((n:any)=>n.pitch===65&&n.start<2);
 await cmd({type:"clearHeldFingerActions",content_id:song.contentId});await cmd({type:"speed",value:1});await cmd({type:"track",id:track,part:"right",mode:"human",visible:true});
 await cmd({type:"editFingersFor",content_id:song.contentId,edits:song.notes.map((n:any)=>({track_id:track,note_index:n.index,finger:n.pitch===65?4:3}))});
 const req={content_id:song.contentId,track,index:held[0].index,hand:"RightHand",profile:"Standard",range:[1,3],keep_saved:true,pins:[],practice_rate:1};
 const plans=await cmd({type:"suggestHeldFingerPlans",request:req}),plan=plans.plans[0];expect(plan.substitutions).toHaveLength(2);
 await cmd({type:"acceptHeldFingerPlan",request:req,fingerprint:plans.fingerprint,edits:plan.proposals.map((p:any)=>({track_id:p.track,note_index:p.index,finger:p.finger})),actions:plan.substitutions});
 await cmd({type:"editFingersFor",content_id:song.contentId,edits:[{track_id:track,note_index:gap.index,finger:null}]});expect((await cmd({type:"currentSong"})).fingerActions.map((a:any)=>a.valid)).toEqual([true,true]);
 await cmd({type:"editFingersFor",content_id:song.contentId,edits:[{track_id:track,note_index:later.index,finger:1}]});expect((await cmd({type:"currentSong"})).fingerActions.map((a:any)=>a.valid)).toEqual([false,true]);
 expect((await raw({type:"heldFingerDemoContext",content_id:song.contentId,track,index:held[0].index,rate:.5})).ok()).toBeFalsy();
 expect((await raw({type:"heldFingerDemoContext",content_id:song.contentId,track,index:held[1].index,rate:.5})).ok()).toBeTruthy();
 const invalid=await cmd({type:"currentSong"}),secondAction=invalid.fingerActions[1];
 const independentEdit={contentId:song.contentId,track,index:held[1].index,originalTick:secondAction.atTick,atTick:secondAction.atTick,to:secondAction.to===1?2:1,baseline:invalid.fingerActionRevision,rate:1};
 const independentlyReviewed=await cmd({type:"reviewHeldActionEdit",request:independentEdit});expect(independentlyReviewed.unrelatedInvalid).toBe(1);
 await cmd({type:"saveHeldActionEdit",request:independentEdit,review:independentlyReviewed.review});expect((await cmd({type:"currentSong"})).fingerActions.map((a:any)=>a.valid)).toEqual([false,true]);
 await cmd({type:"undoFingersFor",content_id:song.contentId});
 await cmd({type:"undoFingersFor",content_id:song.contentId});
 await cmd({type:"noteHand",track,index:held[0].index,part:"LeftHand"});
 expect((await raw({type:"heldFingerDemoContext",content_id:song.contentId,track,index:held[0].index,rate:.5})).ok()).toBeFalsy();
 await cmd({type:"noteHand",track,index:held[0].index,part:"RightHand"});
 const before=await (await request.get("http://127.0.0.1:32124/api/state")).json(),saved=await cmd({type:"currentSong"});
 const ctx=await cmd({type:"heldFingerDemoContext",content_id:song.contentId,track,index:held[0].index,rate:.25});expect(ctx.notes).toHaveLength(3);expect(ctx.actions).toHaveLength(1);
 expect((await raw({type:"startHeldFingerDemo",content_id:song.contentId,track,index:held[0].index,baseline:"stale",rate:.25})).ok()).toBeFalsy();
 await page.goto("/");await expect(page.getByText("本地引擎已连接",{exact:true})).toBeVisible();await page.getByRole("button",{name:"指法建议",exact:true}).click();await page.locator(".held-saved summary").click();await page.getByRole("button",{name:"查看手位示范",exact:true}).first().click();
 const demo=page.getByLabel("持音换指手位示范"),key=demo.locator('g[data-pitch="60"]');await demo.getByLabel("持音换指示范速度").selectOption("0.25");await demo.getByRole("button",{name:"示范此处持音换指",exact:true}).click();
 await expect(demo).toContainText("正在示范持音换指");await expect(key).toHaveAttribute("data-finger","3");await expect(key).toHaveAttribute("data-changed","false");
 await expect.poll(async()=>(await cmd({type:"fingerDemoState"})).position).toBeGreaterThan(.9);await expect(key).toHaveAttribute("data-finger",String(saved.fingerActions[0].to));await expect(key).toHaveAttribute("data-changed","true");
 const during=await (await request.get("http://127.0.0.1:32124/api/state")).json();expect(during.position).toBe(before.position);expect(during.score).toEqual(before.score);expect((await cmd({type:"currentSong"})).fingerActions).toEqual(saved.fingerActions);
 await page.screenshot({path:"../outputs/Neothesia-持音换指声音手位示范.png"});await demo.getByRole("button",{name:"停止换指示范",exact:true}).click();
 await demo.getByRole("button",{name:"换指前手位",exact:true}).click();await expect(key).toHaveAttribute("data-finger","3");await demo.getByRole("button",{name:"换指后手位",exact:true}).click();await expect(key).toHaveAttribute("data-finger",String(saved.fingerActions[0].to));
 await page.setViewportSize({width:1000,height:900});await demo.getByRole("button",{name:"换指后手位",exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:"../outputs/Neothesia-持音换指示范-窄窗.png"});await page.setViewportSize({width:1440,height:960});
 await demo.getByRole("button",{name:"示范此处持音换指",exact:true}).click();await expect(demo).toContainText("正在示范持音换指");await cmd({type:"note",pitch:60,active:true,velocity:80});await expect(demo).toContainText("示范已停止");await cmd({type:"note",pitch:60,active:false,velocity:0});
 await demo.getByRole("button",{name:"示范此处持音换指",exact:true}).click();await expect(demo).toContainText("正在示范持音换指");await page.getByRole("button",{name:"关闭指法建议",exact:true}).click();await expect.poll(async()=>(await cmd({type:"fingerDemoState"})).id).toBeNull();
 await page.getByRole("button",{name:"乐谱",exact:true}).click();const mark=page.locator(".score-practice-substitution").first();await mark.click();const editor=page.getByRole("complementary",{name:"谱面指法编辑"});await editor.getByLabel("持音换指示范速度").selectOption("1");await editor.getByRole("button",{name:"示范此处持音换指",exact:true}).click();await expect(editor).toContainText("示范完成",{timeout:6000});await expect(editor.getByRole("button",{name:"清除此演奏位置的换指",exact:true})).toBeEnabled();
});
