import {test,expect} from "@playwright/test";
test("从历史参考音和所选小节恢复条件重练",async({page,request})=>{
 const cmd=async(data:unknown)=>{const r=await request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});expect(r.ok(),await r.text()).toBeTruthy();return r.json();};const state=async()=>(await request.get("http://127.0.0.1:32124/api/state")).json();
 const xml='<score-partwise><work><work-title>历史问题选段</work-title></work><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1">'+["C","D","E"].map((n,i)=>`<measure number="${i+1}">${i===0?'<attributes><divisions>1</divisions><time><beats>1</beats><beat-type>4</beat-type></time></attributes>':''}<note><pitch><step>${n}</step><octave>4</octave></pitch><duration>1</duration></note></measure>`).join('')+'</part></score-partwise>';
 await cmd({type:"importScore",bytes:[...Buffer.from(xml)],name:"历史问题选段.musicxml",default_bpm:120});const song=await cmd({type:"currentSong"});await cmd({type:"track",id:song.notes[0].track,mode:"human",part:"right",visible:true});await cmd({type:"countIn",bars:0});await cmd({type:"mode",value:"recital"});await cmd({type:"speed",value:.75});await cmd({type:"play"});await expect.poll(async()=>(await state()).position).toBeGreaterThan(.05);await cmd({type:"note",pitch:60,active:true,velocity:80});await cmd({type:"note",pitch:60,active:false,velocity:0});await expect.poll(async()=>(await state()).status).toBe("finished");const count=(await cmd({type:"historyQuery",query:song.title,limit:10})).total;
 await cmd({type:"mode",value:"wait"});await cmd({type:"speed",value:1.25});
 const open=async()=>{await page.getByRole("button",{name:"练习历史",exact:true}).click();await page.getByLabel("查找历史曲目").fill(song.title);await page.locator(".history-record").first().click();const pane=page.locator(".history-performance");await pane.locator("summary").click();await pane.getByRole("button",{name:"查看这次演奏",exact:true}).click();await expect(pane.locator("tbody tr")).toHaveCount(3);return pane;};
 await page.goto("/");let pane=await open();await pane.getByLabel("重练前置小节").selectOption("0");await pane.getByLabel("重练后置小节").selectOption("1");await pane.getByLabel("演奏对照小节").selectOption("2");await expect(pane.locator("tbody tr")).toHaveCount(1);await page.screenshot({path:"../outputs/Neothesia-历史问题选段重练.png"});await pane.getByRole("button",{name:"重练所选小节",exact:true}).click();await expect(page.locator(".history-performance")).toHaveCount(0);let s=await state();expect(s.mode).toBe("flow");expect(s.speed).toBe(.75);expect(s.position).toBe(.5);expect(s.passage.start).toBe(.5);expect(s.passage.end).toBe(1.5);expect(s.status).toBe("ready");expect((await cmd({type:"historyQuery",query:song.title,limit:10})).total).toBe(count);
 pane=await open();await pane.getByLabel("重练前置小节").selectOption("0");await pane.getByLabel("重练后置小节").selectOption("0");await pane.getByRole("button",{name:"重练演奏第 3 小节参考音 3",exact:true}).click();await expect(page.locator(".history-performance")).toHaveCount(0);s=await state();expect(s.passage.start).toBe(1);expect(s.passage.end).toBe(1.5);expect(s.position).toBe(1);await page.screenshot({path:"../outputs/Neothesia-历史选段恢复.png"});await cmd({type:"play"});await expect.poll(async()=>(await state()).position).toBeGreaterThan(1.1);await cmd({type:"pause"});expect((await cmd({type:"historyQuery",query:song.title,limit:10})).total).toBe(count);
});
