import {test,expect} from "@playwright/test";
test("整轮谱面判定分次查看与问题音重练",async({page,request})=>{
 const cmd=async(data:unknown)=>{const r=await request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});expect(r.ok(),await r.text()).toBeTruthy();return r.json();};const state=async()=>(await request.get("http://127.0.0.1:32124/api/state")).json();
 const xml='<score-partwise><work><work-title>历史谱面反复定位</work-title></work><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>1</divisions><time><beats>1</beats><beat-type>4</beat-type></time></attributes><barline location="left"><repeat direction="forward"/></barline><note><pitch><step>C</step><octave>4</octave></pitch><duration>1</duration></note></measure><measure number="2"><note><pitch><step>D</step><octave>4</octave></pitch><duration>1</duration></note><barline location="right"><repeat direction="backward"/></barline></measure><measure number="3"><note><pitch><step>E</step><octave>4</octave></pitch><duration>1</duration></note></measure></part></score-partwise>';
 await cmd({type:"restart"});await cmd({type:"importScore",bytes:[...Buffer.from(xml)],name:"历史谱面反复定位.musicxml",default_bpm:120});const song=await cmd({type:"currentSong"});await cmd({type:"restart"});await cmd({type:"track",id:song.notes[0].track,mode:"human",part:"right",visible:true});await cmd({type:"countIn",bars:0});await cmd({type:"mode",value:"recital"});await cmd({type:"play"});await cmd({type:"note",pitch:60,active:true,velocity:83});await cmd({type:"note",pitch:60,active:false,velocity:0});await expect.poll(async()=>(await state()).status).toBe("finished");const records=await cmd({type:"historyQuery",query:song.title,limit:10});

 await page.goto("/");await page.getByRole("button",{name:"练习历史",exact:true}).click();await page.getByLabel("查找历史曲目").fill(song.title);await page.locator(".history-record").first().click();const pane=page.locator(".history-performance");await pane.locator("summary").click();await pane.getByRole("button",{name:"查看这次演奏",exact:true}).click();await pane.getByRole("button",{name:"整轮谱面批阅",exact:true}).click();
 const review=page.getByLabel("整轮历史谱面批阅");await expect(review).toBeVisible();await expect(page.locator(".history-review-outline")).toHaveCount(3);
 const first=await page.locator('.history-review-note[data-review-reference="0"]').getAttribute("data-review-grade");expect(first).not.toBe("missed");
 await review.getByLabel("谱面历史演奏次数").fill("2");await expect(page.locator(".history-review-outline")).toHaveCount(2);await expect(page.locator('.history-review-note[data-review-reference="2"]')).toHaveAttribute("data-review-grade","missed");
 await review.getByRole("button",{name:"下一问题音",exact:true}).click();await expect(review.getByLabel("谱面历史演奏次数")).toHaveValue("1");await review.getByRole("button",{name:"下一问题音",exact:true}).click();await expect(review.getByLabel("谱面历史演奏次数")).toHaveValue("2");
 await review.locator("summary").click();await expect(review.locator("tbody tr")).toHaveCount(2);await review.getByLabel("谱面批阅重练前置小节").selectOption("0");await review.getByLabel("谱面批阅重练后置小节").selectOption("0");
 await page.screenshot({path:"../outputs/Neothesia-整轮历史谱面批阅.png"});await page.setViewportSize({width:1000,height:900});await page.screenshot({path:"../outputs/Neothesia-整轮历史谱面批阅-窄窗.png"});
 await review.locator("tbody tr").first().getByRole("button",{name:"重练这段",exact:true}).click();await expect(review).toHaveCount(0);await expect(page.locator(".history-review-outline")).toHaveCount(0);await expect(page.locator(".score-history-focus")).toContainText("演奏第 3 小节");const s=await state();expect(s.position).toBe(1);expect(s.passage.start).toBe(1);expect(s.passage.end).toBe(1.5);expect(s.mode).toBe("flow");expect((await cmd({type:"historyQuery",query:song.title,limit:10})).total).toBe(records.total);
});
