import {test,expect} from "@playwright/test";
test("历史和谱面回放暂停、定位、续播与独立计分",async({page,request})=>{
 const cmd=async(data:unknown)=>{const r=await request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});expect(r.ok(),await r.text()).toBeTruthy();return r.json();};const state=async()=>(await request.get("http://127.0.0.1:32124/api/state")).json();
 const xml='<score-partwise><work><work-title>历史谱面反复定位</work-title></work><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>1</divisions><time><beats>1</beats><beat-type>4</beat-type></time></attributes><barline location="left"><repeat direction="forward"/></barline><note><pitch><step>C</step><octave>4</octave></pitch><duration>1</duration></note></measure><measure number="2"><note><pitch><step>D</step><octave>4</octave></pitch><duration>1</duration></note><barline location="right"><repeat direction="backward"/></barline></measure><measure number="3"><note><pitch><step>E</step><octave>4</octave></pitch><duration>1</duration></note></measure></part></score-partwise>';
 await cmd({type:"restart"});await cmd({type:"importScore",bytes:[...Buffer.from(xml)],name:"历史谱面反复定位.musicxml",default_bpm:120});const song=await cmd({type:"currentSong"});await cmd({type:"restart"});await cmd({type:"track",id:song.notes[0].track,mode:"human",part:"right",visible:true});await cmd({type:"countIn",bars:0});await cmd({type:"mode",value:"recital"});await cmd({type:"play"});await cmd({type:"note",pitch:60,active:true,velocity:83});await cmd({type:"note",pitch:60,active:false,velocity:0});await expect.poll(async()=>(await state()).status).toBe("finished");const records=await cmd({type:"historyQuery",query:song.title,limit:10});

 await page.goto("/");await page.getByRole("button",{name:"练习历史",exact:true}).click();await page.getByLabel("查找历史曲目").fill(song.title);await page.locator(".history-record").first().click();const pane=page.locator(".history-performance");await pane.locator("summary").click();await pane.getByRole("button",{name:"查看这次演奏",exact:true}).click();await pane.getByRole("button",{name:"整轮谱面批阅",exact:true}).click();
 const review=page.getByLabel("整轮历史谱面批阅");await expect(review).toBeVisible();await expect(page.locator(".history-review-outline")).toHaveCount(3);
 const first=await page.locator('.history-review-note[data-review-reference="0"]').getAttribute("data-review-grade");expect(first).not.toBe("missed");

 const beforeReplay=await state();const replay=review.getByLabel("谱面历史声音回放");await replay.getByLabel("谱面回放来源").selectOption("reference");await replay.getByLabel("谱面回放速度").selectOption("0.25");await replay.getByRole("button",{name:"随谱回放",exact:true}).click();await expect(page.locator('.history-replay-cursor[data-replay-reference="2"]')).toHaveCount(1,{timeout:8000});await expect(review.getByLabel("谱面历史演奏次数")).toHaveValue("2");expect((await state()).position).toBe(beforeReplay.position);expect((await state()).score).toEqual(beforeReplay.score);

 await replay.getByRole("button",{name:"暂停回放",exact:true}).click();await expect(replay).toContainText("已暂停");const paused=await cmd({type:"fingerDemoState"});expect(paused.paused).toBe(true);await expect.poll(async()=>(await cmd({type:"fingerDemoState"})).position).toBe(paused.position);
 await replay.getByLabel("谱面回放定位秒数").fill("0.25");await replay.getByRole("button",{name:"定位回放",exact:true}).click();await expect(review.getByLabel("谱面历史演奏次数")).toHaveValue("1");expect((await cmd({type:"fingerDemoState"})).position).toBe(.25);expect((await cmd({type:"fingerDemoState"})).paused).toBe(true);
 await replay.getByLabel("谱面回放速度").selectOption("0.5");await replay.getByRole("button",{name:"继续回放",exact:true}).click();await expect.poll(async()=>(await cmd({type:"fingerDemoState"})).position).toBeGreaterThan(.25);await replay.getByRole("button",{name:"暂停回放",exact:true}).click();const bar=await replay.getByLabel("谱面回放进度").boundingBox();expect(bar).not.toBeNull();await replay.getByLabel("谱面回放进度").click({position:{x:bar!.width*.6,y:bar!.height/2}});await expect.poll(async()=>(await cmd({type:"fingerDemoState"})).position).toBeGreaterThan(1.5);await replay.getByLabel("谱面回放定位秒数").fill("1");await replay.getByRole("button",{name:"定位回放",exact:true}).click();await expect(review.getByLabel("谱面历史演奏次数")).toHaveValue("2");
 await page.screenshot({path:"../outputs/Neothesia-历史回放暂停定位.png"});await page.setViewportSize({width:1000,height:900});await page.screenshot({path:"../outputs/Neothesia-历史回放暂停定位-窄窗.png"});
 await replay.getByRole("button",{name:"停止回放",exact:true}).click();await expect(page.locator(".history-replay-cursor")).toHaveCount(0);await expect(page.locator(".history-review-note")).toHaveCount(2);
 await replay.getByLabel("谱面回放来源").selectOption("actual");await replay.getByRole("button",{name:"随谱回放",exact:true}).click();await expect(replay).toContainText("正在回放");await cmd({type:"note",pitch:65,active:true,velocity:90});await expect(replay).toContainText("已停止");await cmd({type:"note",pitch:65,active:false,velocity:0});

 await review.getByRole("button",{name:"结束谱面批阅",exact:true}).click();await page.getByRole("button",{name:"练习历史",exact:true}).click();await page.getByLabel("查找历史曲目").fill(song.title);await page.locator(".history-record").first().click();const historyPane=page.locator(".history-performance");await historyPane.locator("summary").click();await historyPane.getByRole("button",{name:"查看这次演奏",exact:true}).click();await historyPane.getByLabel("历史回放来源").selectOption("reference");await historyPane.getByRole("button",{name:"回放声音",exact:true}).click();await historyPane.getByRole("button",{name:"暂停回放",exact:true}).click();await historyPane.getByLabel("历史回放定位秒数").fill("1.5");await historyPane.getByRole("button",{name:"定位回放",exact:true}).click();expect((await cmd({type:"fingerDemoState"})).position).toBe(1.5);await historyPane.getByRole("button",{name:"继续回放",exact:true}).click();await expect(historyPane).toContainText("正在回放");await historyPane.getByRole("button",{name:"停止回放",exact:true}).click();expect((await state()).position).toBe(beforeReplay.position);expect((await state()).score).toEqual(beforeReplay.score);expect((await cmd({type:"historyQuery",query:song.title,limit:10})).total).toBe(records.total);
});
