import {test,expect} from "@playwright/test";
test("保存真实按键并从历史对照、独立回放和接管",async({page,request})=>{
 const cmd=async(data:unknown)=>{const r=await request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});expect(r.ok(),await r.text()).toBeTruthy();return r.json();};const state=async()=>(await request.get("http://127.0.0.1:32124/api/state")).json();
 let title="历史演奏对照"+Date.now();const xml=`<score-partwise><work><work-title>${title}</work-title></work><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>1</divisions><time><beats>2</beats><beat-type>4</beat-type></time></attributes><note><pitch><step>C</step><octave>4</octave></pitch><duration>2</duration></note></measure><measure number="2"><note><pitch><step>D</step><octave>4</octave></pitch><duration>2</duration></note></measure></part></score-partwise>`;
 await cmd({type:"importScore",bytes:[...Buffer.from(xml)],name:title+".musicxml",default_bpm:120});const song=await cmd({type:"currentSong"});title=song.title;await cmd({type:"track",id:song.notes[0].track,mode:"human",part:"right",visible:true});await cmd({type:"mode",value:"flow"});await cmd({type:"countIn",bars:0});await cmd({type:"play"});await expect.poll(async()=>(await state()).position).toBeGreaterThan(.05);await cmd({type:"note",pitch:60,active:true,velocity:83});await expect.poll(async()=>(await state()).position).toBeGreaterThan(.3);await cmd({type:"note",pitch:60,active:false,velocity:0});await expect.poll(async()=>(await state()).status).toBe("finished");
 const history=await cmd({type:"historyQuery",query:title,limit:10});const record=history.entries[0];const archive=await cmd({type:"historyPerformance",content_id:song.contentId,id:record.id});expect(archive.references).toHaveLength(2);expect(archive.inputs.filter((n:any)=>n.bytes[0]===144&&n.bytes[1]===60)).toHaveLength(1);expect(archive.inputs.some((n:any)=>n.bytes[0]===128&&n.bytes[1]===60)).toBeTruthy();const before=await state();
 await page.goto("/");await page.getByRole("button",{name:"练习历史",exact:true}).click();await page.getByLabel("查找历史曲目").fill(title);await page.locator(".history-record").first().click();const pane=page.locator(".history-performance");await pane.locator("summary").click();await pane.getByRole("button",{name:"查看这次演奏",exact:true}).click();await expect(pane.getByLabel("参考与实际按键时间线")).toBeVisible();await expect(pane.locator("tbody tr")).toHaveCount(2);await pane.getByLabel("演奏对照小节").selectOption("2");await expect(pane.locator("tbody tr")).toHaveCount(1);await expect(pane.locator(".history-performance-table")).toContainText("漏音");await pane.getByLabel("演奏对照小节").selectOption("0");await pane.getByRole("button",{name:"回放声音",exact:true}).click();await expect(pane).toContainText("正在回放");await expect.poll(async()=>(await cmd({type:"fingerDemoState"})).position).toBeGreaterThan(.2);const during=await state();expect(during.position).toBe(before.position);expect(during.score).toEqual(before.score);await pane.scrollIntoViewIfNeeded();await page.screenshot({path:"../outputs/Neothesia-历史演奏回放对照.png"});
 await cmd({type:"note",pitch:65,active:true,velocity:90});await expect(pane).toContainText("已停止");await cmd({type:"note",pitch:65,active:false,velocity:0});await pane.getByLabel("历史回放来源").selectOption("reference");await pane.getByLabel("历史回放速度").selectOption("1");await pane.getByRole("button",{name:"回放声音",exact:true}).click();await expect(pane).toContainText("正在回放");await page.setViewportSize({width:1000,height:900});await pane.scrollIntoViewIfNeeded();await page.screenshot({path:"../outputs/Neothesia-历史演奏回放对照-窄窗.png"});await pane.locator("summary").click();await expect.poll(async()=>(await cmd({type:"fingerDemoState"})).id).toBeNull();expect((await cmd({type:"historyQuery",query:title,limit:10})).total).toBe(history.total);
});
