import {test,expect} from "@playwright/test";
test("整体缩放、窗口适配、键盘点按与重开保存",async({page,request})=>{
 const cmd=async(data:unknown)=>{const r=await request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});expect(r.ok(),await r.text()).toBeTruthy();return r.json()};const state=async()=> (await request.get("http://127.0.0.1:32124/api/state")).json();await cmd({type:"generate",spec:{tonic:0,tonality:"Major",minor_form:"Natural",pattern:"Scale",direction:"UpAndDown",hands:"Both",octaves:1,repetitions:1,tempo_bpm:120}});
 await page.goto("/");await page.getByLabel("显示与电脑键盘设置").click();const d=page.getByRole("dialog",{name:"显示与电脑键盘"}),layout=d.getByRole("region",{name:"练习室布局"});await layout.getByLabel("整体界面缩放").selectOption("150");await expect(page.locator("html")).toHaveCSS("zoom","1.5");await layout.scrollIntoViewIfNeeded();await page.screenshot({path:"../outputs/Neothesia-整体界面缩放.png"});await d.getByRole("button",{name:"完成",exact:true}).click();
 await page.setViewportSize({width:1800,height:960});const handle=page.getByRole("separator",{name:"调整曲库宽度"}),hb=await handle.boundingBox();await page.mouse.move(hb!.x+3,hb!.y+100);await page.mouse.down();await page.mouse.move(hb!.x+33,hb!.y+100);await page.mouse.up();await expect(page.locator(".library-panel")).toHaveCSS("width","290px");
 const canvas=page.getByLabel("按小节排列的音符与可演奏键盘"),box=await canvas.boundingBox();await page.mouse.move(box!.x+box!.width*.5,box!.y+box!.height-10);await page.mouse.down();await expect.poll(async()=> (await state()).pressed).toEqual([60]);await page.mouse.up();await expect.poll(async()=> (await state()).pressed.length).toBe(0);
 await page.keyboard.press("Alt+Shift+-");await expect(page.locator("html")).toHaveCSS("zoom","1.4");await page.keyboard.press("Alt+Shift+=");await expect(page.locator("html")).toHaveCSS("zoom","1.5");await page.reload();await expect(page.locator("html")).toHaveCSS("zoom","1.5");await page.keyboard.press("Alt+Shift+0");await expect(page.locator("html")).toHaveCSS("zoom","1");
 await page.setViewportSize({width:700,height:900});await page.getByLabel("显示与电脑键盘设置").click();await layout.getByLabel("整体界面缩放").selectOption("150");const bounds=await d.boundingBox();expect(bounds!.width).toBeLessThanOrEqual(701);expect(bounds!.height).toBeLessThanOrEqual(901);await layout.scrollIntoViewIfNeeded();await page.screenshot({path:"../outputs/Neothesia-整体界面缩放-窄窗.png"});await layout.getByRole("button",{name:"适应当前窗口",exact:true}).click();await expect(page.locator("html")).toHaveCSS("zoom","0.8");await layout.getByRole("button",{name:"恢复 100% 缩放",exact:true}).click();await expect(page.locator("html")).toHaveCSS("zoom","1");
});
test("旧界面备份补缩放默认与非法缩放拒绝",async({page})=>{await page.goto("/");const r=await page.evaluate(async()=>{const m=await import("/src/interfaceBackup.ts"),p=await import("/src/displayPreferences.ts");const old:any=m.interfaceSnapshot(p.readDisplayPreferences());delete old.preferences.uiScale;for(const id of ["zoomIn","zoomOut","zoomReset"])delete old.preferences.shortcuts[id];old.layouts=[{id:"old",name:"旧读谱方案",layout:{libraryOpen:true,inspector:true,libraryWidth:270,inspectorWidth:218,keyboardHeight:100,paperPreviewHeight:150}}];const decoded=m.decodeInterfaceBackup(JSON.stringify(old));let error="";old.preferences.uiScale=300;try{m.decodeInterfaceBackup(JSON.stringify(old));}catch(e){error=String(e);}return {scale:decoded.preferences.uiScale,layout:decoded.layouts[0].layout.uiScale,key:decoded.preferences.shortcuts.zoomReset,error};});expect(r.scale).toBe(100);expect(r.layout).toBe(100);expect(r.key).toBe("Alt+Shift+Digit0");expect(r.error).toContain("无效");});
