import {test,expect} from "@playwright/test";
import {readFile} from "node:fs/promises";
test("界面设置备份下载、差异恢复、同名布局与陈旧保护",async({page})=>{
 await page.goto("/");await page.getByLabel("显示与电脑键盘设置").click();const d=page.getByRole("dialog",{name:"显示与电脑键盘"}),layout=d.getByRole("region",{name:"练习室布局"}),backup=d.getByRole("region",{name:"界面设置备份"});await layout.getByLabel("琴键高度",{exact:true}).fill("180");await layout.getByLabel("布局名称",{exact:true}).fill("教师读谱");await layout.getByRole("button",{name:"另存当前布局",exact:true}).click();
 const download=page.waitForEvent("download");await backup.getByRole("button",{name:"导出界面设置",exact:true}).click();const file=await download;const raw=await readFile((await file.path())!,"utf8"),data=JSON.parse(raw);expect(data.preferences.keyboardHeight).toBe(180);expect(data.layouts).toHaveLength(1);
 await layout.getByLabel("琴键高度",{exact:true}).fill("100");await layout.getByRole("button",{name:"更新当前布局",exact:true}).click();
 const upload=async(text:string)=>backup.getByLabel("界面设置备份文件").setInputFiles({name:"教师设置.neosettings",mimeType:"application/json",buffer:Buffer.from(text)});
 await upload(raw);await expect(backup.locator("p[role=status]")).toContainText("已读取备份");await expect(backup.getByLabel("恢复布局：教师读谱")).toHaveValue("keep");await backup.getByText("核对显示与面板差异",{exact:true}).click();await backup.scrollIntoViewIfNeeded();await page.screenshot({path:"../outputs/Neothesia-界面设置备份.png"});await page.setViewportSize({width:700,height:900});await backup.scrollIntoViewIfNeeded();await page.screenshot({path:"../outputs/Neothesia-界面设置备份-窄窗.png"});await page.setViewportSize({width:1440,height:960});
 await layout.getByLabel("琴键高度",{exact:true}).fill("120");await backup.getByRole("button",{name:"恢复所选设置",exact:true}).click();await expect(backup.getByRole("alert")).toContainText("已变化");await expect(layout.getByLabel("琴键高度",{exact:true})).toHaveValue("120");await backup.getByRole("button",{name:"重新核对本机设置",exact:true}).click();await backup.getByLabel("恢复电脑键盘弹奏").uncheck();await backup.getByLabel("恢复操作快捷键").uncheck();await backup.getByRole("button",{name:"恢复所选设置",exact:true}).click();await expect(backup.locator("p[role=status]")).toHaveText("所选界面设置已恢复");await expect(layout.getByLabel("琴键高度",{exact:true})).toHaveValue("180");expect(await page.evaluate(()=>JSON.parse(localStorage.getItem("neothesia-layouts-v1")!)[0].layout.keyboardHeight)).toBe(100);
 await upload(raw);await backup.getByLabel("恢复布局：教师读谱").selectOption("replace");await backup.getByRole("button",{name:"恢复所选设置",exact:true}).click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem("neothesia-layouts-v1")!)[0].layout.keyboardHeight)).toBe(180);
 const bad=structuredClone(data);bad.version=999;await upload(JSON.stringify(bad));await expect(backup.getByRole("alert")).toContainText("版本");
 const conflicting=structuredClone(data);conflicting.preferences.shortcuts.silence="KeyZ";await d.getByRole("button",{name:"Z X C 行",exact:true}).click();await upload(JSON.stringify(conflicting));await backup.getByLabel("恢复电脑键盘弹奏").uncheck();await backup.getByRole("button",{name:"恢复所选设置",exact:true}).click();await expect(backup.getByRole("alert")).toContainText("快捷键与弹奏键冲突");
});
test("界面设置写入中断回退与无效绑定拒绝",async({page})=>{
 await page.goto("/");const result=await page.evaluate(async()=>{const m=await import("/src/interfaceBackup.ts"),p=await import("/src/displayPreferences.ts"),l=await import("/src/LayoutSettings.tsx");const current=p.readDisplayPreferences();localStorage.setItem(p.displayStorage,JSON.stringify(current));localStorage.setItem(l.layoutStorage,"[]");const before=localStorage.getItem(p.displayStorage),backup=m.interfaceSnapshot(current);backup.preferences.keyboardHeight=200;const baseline=m.interfaceBaseline(current);localStorage.setItem(p.displayStorage,JSON.stringify({...current,fontSize:14}));let stale="";try{m.restoreInterface(backup,current,baseline,{display:true,keyboard:false,shortcuts:false},{});}catch(e){stale=String(e);}localStorage.setItem(p.displayStorage,before!);const original=Storage.prototype.setItem;let fail=true;Storage.prototype.setItem=function(k,v){if(k===l.layoutStorage&&fail){fail=false;throw new Error("write failure");}return original.call(this,k,v);};let error="";try{m.restoreInterface(backup,current,baseline,{display:true,keyboard:false,shortcuts:false},{});}catch(e){error=String(e);}finally{Storage.prototype.setItem=original;}let invalid="";backup.preferences.shortcuts.playPause="KeyA";try{m.decodeInterfaceBackup(JSON.stringify(backup));}catch(e){invalid=String(e);}return {error,invalid,stale,rolledBack:localStorage.getItem(p.displayStorage)===before,layouts:localStorage.getItem(l.layoutStorage)};});expect(result.stale).toContain("已变化");expect(result.error).toContain("已回退");expect(result.rolledBack).toBeTruthy();expect(result.layouts).toBe("[]");expect(result.invalid).toContain("冲突");
});
