import {test,expect} from "@playwright/test";
test("布局方案、尺寸恢复与侧栏调整",async({page,request})=>{
 const cmd=async(data:unknown)=>{const r=await request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});expect(r.ok(),await r.text()).toBeTruthy();return r.json()};
 await cmd({type:"generate",spec:{tonic:0,tonality:"Major",minor_form:"Natural",pattern:"Scale",direction:"UpAndDown",hands:"Both",octaves:1,repetitions:1,tempo_bpm:120}});
 await page.goto("/");await page.getByLabel("显示与电脑键盘设置").click();const d=page.getByRole("dialog",{name:"显示与电脑键盘"}),layout=d.getByRole("region",{name:"练习室布局"});
 await layout.getByLabel("曲库宽度",{exact:true}).fill("320");await layout.getByLabel("练习参数宽度",{exact:true}).fill("250");await layout.getByLabel("琴键高度",{exact:true}).fill("160");await layout.getByLabel("纸谱上方键盘区域",{exact:true}).fill("220");
 const name="读谱 · 宽曲库";await layout.getByLabel("布局名称",{exact:true}).fill(name);await layout.getByRole("button",{name:"另存当前布局",exact:true}).click();await expect(layout.locator("p[role=status]")).toHaveText("当前布局已另存");await layout.scrollIntoViewIfNeeded();await page.screenshot({path:"../outputs/Neothesia-练习室布局方案.png"});
 await layout.getByRole("button",{name:"专注练习",exact:true}).click();await d.getByRole("button",{name:"完成",exact:true}).click();await expect(page.locator(".library-panel")).toHaveCount(0);await expect(page.locator(".practice-inspector")).toHaveCount(0);
 await page.reload();await page.getByLabel("显示与电脑键盘设置").click();await layout.getByLabel("已保存布局",{exact:true}).selectOption({label:name});await layout.getByRole("button",{name:"应用布局",exact:true}).click();await expect(layout.getByLabel("琴键高度",{exact:true})).toHaveValue("160");await d.getByRole("button",{name:"完成",exact:true}).click();await expect(page.getByLabel("显示与电脑键盘设置")).toBeFocused();await expect(page.locator(".library-panel")).toHaveCSS("width","320px");await expect(page.locator(".practice-inspector")).toHaveCSS("width","250px");
 const sep=page.getByRole("separator",{name:"调整曲库宽度"});await sep.focus();await page.keyboard.press("ArrowRight");await expect(page.locator(".library-panel")).toHaveCSS("width","330px");const bounds=await sep.boundingBox();await page.mouse.move(bounds!.x+3,bounds!.y+100);await page.mouse.down();await page.mouse.move(bounds!.x+33,bounds!.y+100);await page.mouse.up();await expect(page.locator(".library-panel")).toHaveCSS("width","360px");
 const canvas=page.getByLabel("按小节排列的音符与可演奏键盘");const box=await canvas.boundingBox();await page.mouse.move(box!.x+box!.width*.5,box!.y+box!.height-130);await page.mouse.down();await expect.poll(async()=> (await (await request.get("http://127.0.0.1:32124/api/state")).json()).pressed.length).toBeGreaterThan(0);await page.mouse.up();await expect.poll(async()=> (await (await request.get("http://127.0.0.1:32124/api/state")).json()).pressed.length).toBe(0);
 await page.getByLabel("显示与电脑键盘设置").click();await layout.getByLabel("已保存布局",{exact:true}).selectOption({label:name});await layout.getByLabel("布局名称",{exact:true}).fill(name+"新");await layout.getByRole("button",{name:"仅改名",exact:true}).click();await expect(layout.getByLabel("已保存布局").locator("option:checked")).toHaveText(name+"新");await page.setViewportSize({width:700,height:900});await layout.scrollIntoViewIfNeeded();await page.screenshot({path:"../outputs/Neothesia-练习室布局方案-窄窗.png"});await layout.getByRole("button",{name:"删除布局",exact:true}).click();await expect(layout.locator("p[role=status]")).toContainText("布局已删除");
 const prefs=await page.evaluate(()=>JSON.parse(localStorage.getItem("neothesia-display-v1")??"{}"));expect(prefs.keyCodes).toHaveLength(13);expect(prefs.keyboardHeight).toBe(160);
});
