import {test,expect} from "@playwright/test";
import {mkdir,writeFile,rename} from "node:fs/promises";
import {resolve} from "node:path";
test("全库纸谱原件后台发现、集中预览采用、忽略和迁址保护",async({page,request})=>{
 const raw=(data:unknown)=>request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});
 const cmd=async(data:unknown)=>{const r=await raw(data);expect(r.ok(),await r.text()).toBeTruthy();return r.json();};
 const png=async(text:string)=>Buffer.from(await page.evaluate(text=>{const c=document.createElement("canvas");c.width=600;c.height=400;const x=c.getContext("2d")!;x.fillStyle="white";x.fillRect(0,0,600,400);x.fillStyle="black";x.font="30px sans-serif";x.fillText(text,50,100);return c.toDataURL("image/png").split(",")[1];},text),"base64");
 await cmd({type:"setLibraryMonitor",enabled:false});
 const folder=resolve(`../work/cycle167-sources-${Date.now()}`);await mkdir(folder,{recursive:true});const first=await png("教师谱页 A · 原稿 "+Date.now()),second=await png("教师谱页 B · 原稿"),newer=await png("教师谱页 A · 修订");
 const setup=async(step:string,name:string,bytes:Buffer)=>{const xml=`<score-partwise><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time></attributes><note><pitch><step>${step}</step><octave>4</octave></pitch><duration>4</duration></note></measure></part></score-partwise>`;const imported=await cmd({type:"importScore",name:name+".musicxml",bytes:[...Buffer.from(xml)],default_bpm:80});const song=await cmd({type:"currentSong"});const papers=await cmd({type:"addScoreAttachment",content_id:song.contentId,name:name+".png",bytes:[...bytes],append:null});const a=papers.attachments.find((a:any)=>a.id===papers.active);const path=resolve(folder,name+".png");await writeFile(path,bytes);await cmd({type:"linkPaperSource",content_id:song.contentId,book:a.id,asset:a.pages[0].id,path});return {cid:song.contentId,book:a.id,asset:a.pages[0].id,path,midiPath:imported.sourcePath,count:papers.attachments.length};};
 const prefix=String(Date.now());const a=await setup("C",prefix+"原件监控甲",first),b=await setup("D",prefix+"原件监控乙",second);const relevant=async()=>{const s=await cmd({type:"paperSourceUpdates"});return s.rows.filter((r:any)=>[a.cid,b.cid].includes(r.contentId)&&[a.book,b.book].includes(r.book));};
 await cmd({type:"refreshLibrary"});await expect.poll(async()=>(await relevant()).map((r:any)=>r.status).sort(),{timeout:15000}).toEqual(["same","same"]);
 await writeFile(a.path,newer);const moved=resolve(folder,"乙搬家.png");await rename(b.path,moved);await cmd({type:"setLibraryMonitor",enabled:true});
 await expect.poll(async()=>(await relevant()).map((r:any)=>r.status).sort(),{timeout:15000}).toEqual(["changed","missing"]);
 const stale=(await relevant()).find((r:any)=>r.book===b.book);await cmd({type:"updateScoreAttachment",content_id:b.cid,id:b.book,action:"rename",name:prefix+"监控乙已改名",view:null,page:0,direction:0});expect((await raw({type:"linkPaperSource",content_id:b.cid,book:b.book,asset:b.asset,path:moved,baseline:stale.baseline})).ok()).toBeFalsy();
 await page.goto("/");await page.getByRole("button",{name:"曲库管理",exact:true}).click();await page.getByRole("button",{name:/^纸谱原件/}).click();const dialog=page.getByRole("dialog",{name:"纸谱原件"});await dialog.getByLabel("搜索纸谱原件").fill(prefix+"原件监控甲");await dialog.getByRole("button",{name:"查看与处理",exact:true}).click();await dialog.getByRole("button",{name:"预览原件更新",exact:true}).click();const preview=dialog.getByRole("region",{name:"集中原件更新预览"});await expect(preview.locator("canvas")).toBeVisible();await dialog.evaluate(el=>el.scrollTop=0);await page.screenshot({path:"../outputs/Neothesia-纸谱原件集中更新.png"});
 await preview.getByRole("button",{name:"保存为新版本",exact:true}).click();await expect(dialog).toContainText("已保存新版本");const books=(await cmd({type:"libraryScores",content_id:a.cid,path:a.midiPath})).papers;expect(books.attachments).toHaveLength(a.count+1);expect(books.attachments.find((v:any)=>v.id===a.book).pages[0].id).toBe(a.asset);
 // Old source stays visible for comparison until the specific update is acknowledged.
 await expect(dialog.getByRole("button",{name:"预览原件更新",exact:true})).toBeEnabled();await dialog.getByRole("button",{name:"预览原件更新",exact:true}).click();await dialog.getByRole("button",{name:"忽略这次更新",exact:true}).click();await expect.poll(async()=>(await relevant()).find((r:any)=>r.book===a.book)?.status,{timeout:15000}).toBe("ignored");
 await dialog.getByLabel("搜索纸谱原件").fill(prefix+"监控乙已改名");await dialog.getByRole("button",{name:"查看与处理",exact:true}).click();await dialog.getByLabel("纸谱原件新位置").fill(moved);await dialog.getByRole("button",{name:"关联相同内容的新位置",exact:true}).click();await expect.poll(async()=>(await relevant()).find((r:any)=>r.book===b.book)?.status,{timeout:15000}).toBe("same");
 await dialog.getByLabel("纸谱原件状态").selectOption("all");await expect(dialog).toContainText("与副本一致");
 await page.setViewportSize({width:1000,height:900});await dialog.getByLabel("纸谱原件新位置").scrollIntoViewIfNeeded();await page.screenshot({path:"../outputs/Neothesia-纸谱原件集中更新-窄窗.png"});
 await dialog.getByRole("button",{name:"解除原件关联",exact:true}).click();await expect.poll(async()=>(await relevant()).some((r:any)=>r.book===b.book),{timeout:15000}).toBeFalsy();expect((await cmd({type:"libraryScores",content_id:b.cid,path:b.midiPath})).papers.attachments).toHaveLength(b.count);
 await writeFile(a.path,second);await expect.poll(async()=>(await relevant()).find((r:any)=>r.book===a.book)?.status,{timeout:15000}).toBe("changed");
});
