import {test,expect} from "@playwright/test";
test("多个精确段落编排、重复与审阅更新、当天独立进度",async({page,request})=>{
 const cmd=async(data:unknown)=>{const r=await request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});expect(r.ok(),await r.text()).toBeTruthy();return r.json()};const state=async()=>(await request.get("http://127.0.0.1:32124/api/state")).json();
 const xml=`<score-partwise><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1">${[1,2,3].map(n=>`<measure number="${n}">${n===1?'<attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time></attributes><direction><sound tempo="240"/></direction>':''}${['C','D','E','F'].map(step=>`<note><pitch><step>${step}</step><octave>4</octave></pitch><duration>1</duration></note>`).join('')}</measure>`).join('')}</part></score-partwise>`;
 await cmd({type:"importScore",name:"分散短句编排.musicxml",bytes:[...Buffer.from(xml)],default_bpm:240});await cmd({type:"mode",value:"wait"});await cmd({type:"countIn",bars:0});const song=await cmd({type:"currentSong"});await cmd({type:"track",id:song.notes[0].track,mode:"human",part:"right",visible:true});
 for(const p of (await cmd({type:"passages"})).passages){if(["开头放松","结尾连接"].includes(p.name))await cmd({type:"removePassage",id:p.id})}
 await cmd({type:"speed",value:.6});await cmd({type:"savePassage",id:null,name:"开头放松",start:1,end:1,notes:"保持手腕放松"});
 await cmd({type:"speed",value:.85});const timing=await cmd({type:"passages"});const preview=await cmd({type:"previewTickRange",content_id:song.contentId,grid:timing.grid,start:{measure:3,beat:1.5},end:{measure:3,beat:3.5}});await cmd({type:"saveTickPassage",id:null,name:"结尾连接",notes:"稳定衔接",range:preview.range});
 await page.goto("/");await page.getByRole("button",{name:"练习计划",exact:true}).click();await page.getByRole("button",{name:"常用计划",exact:true}).click();await page.getByLabel("练习计划名称").fill("分散短句日课");await page.getByRole("button",{name:"创建计划",exact:true}).click();await page.getByRole("button",{name:"编排多个段落",exact:true}).click();const d=page.getByRole("dialog",{name:"编排多个段落",exact:true});await d.getByRole("button",{name:/加入编排：.* \/ 开头放松$/}).click();await d.getByRole("button",{name:/加入编排：.* \/ 结尾连接$/}).click();await d.getByRole("button",{name:"上移第 2 段",exact:true}).click();await d.getByLabel("第 1 段编排次数").fill("2");await d.getByRole("button",{name:"核对编排",exact:true}).click();await expect(d.getByRole("status")).toContainText("追加 3 项");await d.getByLabel("编排最低正确率").fill("95");await expect(d.getByRole("button",{name:"按此顺序加入计划",exact:true})).toBeDisabled();await d.getByRole("button",{name:"核对编排",exact:true}).click();page.once("dialog",d=>d.dismiss());await page.keyboard.press("Escape");await expect(d).toBeVisible();await page.screenshot({path:"../outputs/Neothesia-多段练习编排.png"});await page.setViewportSize({width:680,height:900});await page.screenshot({path:"../outputs/Neothesia-多段练习编排-窄窗.png"});await page.setViewportSize({width:1440,height:960});await d.getByRole("button",{name:"按此顺序加入计划",exact:true}).click();await expect(d).toHaveCount(0);await expect(page.locator(".routine-item")).toHaveCount(3);await expect(page.locator(".routine-item").first()).toContainText("结尾连接 · 1/2");
 await page.getByRole("button",{name:"当天安排",exact:true}).click();await page.getByLabel("练习计划日期").fill("2026-10-02");await page.locator(".routine-item-select").first().click();await page.getByRole("button",{name:"打开本项练习",exact:true}).click();const loaded=await state();expect(loaded.speed).toBe(.85);expect(loaded.routine.goal.accuracy).toBe(95);expect(loaded.passage.end-loaded.passage.start).toBeCloseTo(.5);
 await cmd({type:"play"});await expect.poll(async()=>{const s=await state();for(const pitch of s.required){await cmd({type:"note",pitch,velocity:90,active:true});await cmd({type:"note",pitch,velocity:0,active:false})}return (await state()).routine?.progress.completed},{timeout:15000}).toBe(true);await page.getByRole("button",{name:"打开下一项",exact:true}).click();await expect(page.locator(".routine-status")).toContainText("结尾连接 · 2/2");expect((await state()).routine.progress.attempts).toBe(0);await cmd({type:"stopRoutine"});
});
