import {test,expect} from "@playwright/test";
test("回放随成绩备份、冲突预览、保留与恢复",async({page,request})=>{
 const cmd=async(data:unknown)=>{const r=await request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});expect(r.ok(),await r.text()).toBeTruthy();return r.json();};
 const state=async()=>(await request.get("http://127.0.0.1:32124/api/state")).json();
 const xml='<score-partwise><work><work-title>演奏迁移课堂</work-title></work><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>1</divisions><time><beats>2</beats><beat-type>4</beat-type></time></attributes><note><pitch><step>E</step><octave>4</octave></pitch><duration>2</duration></note></measure></part></score-partwise>';
 await cmd({type:"importScore",bytes:[...Buffer.from(xml)],name:"演奏迁移课堂.musicxml",default_bpm:120});const song=await cmd({type:"currentSong"});await cmd({type:"track",id:song.notes[0].track,mode:"human",part:"right",visible:true});await cmd({type:"countIn",bars:0});await cmd({type:"mode",value:"flow"});await cmd({type:"play"});await expect.poll(async()=>(await state()).position).toBeGreaterThan(.05);await cmd({type:"note",pitch:64,active:true,velocity:83});await expect.poll(async()=>(await state()).position).toBeGreaterThan(.3);await cmd({type:"note",pitch:64,active:false,velocity:0});await expect.poll(async()=>(await state()).status).toBe("finished");
 const entry=(await cmd({type:"historyQuery",query:song.title,limit:10})).entries[0];const selection={plans:false,records:true,presets:false,days:0};const snapshot=await cmd({type:"practiceBackupSnapshot",selection});expect(snapshot.performances[song.contentId][entry.id].inputs[0].bytes[2]).toBe(83);
 await page.goto("/");await page.getByRole("button",{name:"练习计划",exact:true}).click();await page.getByRole("button",{name:"练习资料备份",exact:true}).click();const dialog=page.getByRole("dialog",{name:"练习资料备份"});await dialog.getByLabel("计划、日课与曲目学习",{exact:true}).uncheck();await dialog.getByLabel("片段、阶梯、技术练习、音轨与资料模板",{exact:true}).uncheck();await expect(dialog.getByLabel("个人成绩与演奏回放",{exact:true})).toBeChecked();
 const promise=page.waitForEvent("download");await dialog.getByRole("button",{name:"导出练习备份",exact:true}).click();const file="../work/cycle169-performance.neopractice";await(await promise).saveAs(file);
 snapshot.performances[song.contentId][entry.id].inputs[0].bytes[2]=99;await cmd({type:"applyPracticeBackup",backup:snapshot,selection,policy:"backup"});
 await dialog.getByLabel("练习备份文件").setInputFiles(file);await expect(dialog.locator(".practice-backup-counts")).toContainText("演奏回放 / 内容冲突");await expect(dialog.locator(".practice-backup-counts div").filter({hasText:"演奏回放 / 内容冲突"})).toContainText("/ 1");await dialog.getByText("查看资料与回放冲突",{exact:true}).click();await expect(dialog.locator("details").filter({hasText:"查看资料与回放冲突"})).toContainText(song.title);await page.screenshot({path:"../outputs/Neothesia-演奏回放备份.png"});await dialog.getByRole("button",{name:"按所选范围导入",exact:true}).click();await expect(dialog.getByRole("status")).toContainText("保留本地 1 次");expect((await cmd({type:"historyPerformance",content_id:song.contentId,id:entry.id})).inputs[0].bytes[2]).toBe(99);
 await dialog.getByLabel("练习备份文件").setInputFiles(file);await expect(dialog.locator(".practice-backup-counts")).toBeVisible();await dialog.getByLabel("练习备份冲突策略").selectOption("backup");await dialog.getByRole("button",{name:"按所选范围导入",exact:true}).click();await expect(dialog.getByRole("status")).toContainText("恢复/替换 1 次");expect((await cmd({type:"historyPerformance",content_id:song.contentId,id:entry.id})).inputs[0].bytes[2]).toBe(83);expect((await cmd({type:"historyQuery",query:song.title,limit:10})).total).toBe(1);
 const replay=await cmd({type:"startHistoryReplay",content_id:song.contentId,id:entry.id,source:"actual",rate:.5});await expect.poll(async()=>(await cmd({type:"fingerDemoState"})).position).toBeGreaterThan(.1);await cmd({type:"stopFingerDemo",id:replay.id});
});
