import {test,expect} from "@playwright/test";
test("反复谱持音换指显示、定位、单位置清除和撤销",async({page,request})=>{
 const raw=(data:unknown)=>request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});
 const cmd=async(data:unknown)=>{const r=await raw(data);expect(r.ok(),await r.text()).toBeTruthy();return r.json();};
 const xml=`<score-partwise version="4.0"><work><work-title>反复持音换指课堂</work-title></work><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>2</divisions><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes><barline location="left"><repeat direction="forward"/></barline><note><pitch><step>C</step><octave>4</octave></pitch><duration>8</duration><voice>1</voice><type>whole</type></note><backup><duration>8</duration></backup><forward><duration>4</duration></forward><note><pitch><step>E</step><octave>4</octave></pitch><duration>2</duration><voice>2</voice><type>quarter</type></note><barline location="right"><repeat direction="backward" times="2"/></barline></measure></part></score-partwise>`;
 await cmd({type:"importScore",bytes:[...Buffer.from(xml)],name:"反复持音换指.musicxml",default_bpm:120});
 const song=await cmd({type:"currentSong"}),track=song.notes[0].track;
 expect(song.notes).toHaveLength(4);const sustained=song.notes.filter((n:any)=>n.pitch===60).sort((a:any,b:any)=>a.start-b.start);
 await cmd({type:"clearHeldFingerActions",content_id:song.contentId});await cmd({type:"speed",value:1});
 await cmd({type:"track",id:track,part:"right",mode:"human",visible:true});
 await cmd({type:"editFingersFor",content_id:song.contentId,edits:song.notes.map((n:any)=>({track_id:n.track,note_index:n.index,finger:3}))});
 const req={content_id:song.contentId,track,index:sustained[0].index,hand:"RightHand",profile:"Standard",range:[1,2],keep_saved:true,pins:[],practice_rate:1};
 const result=await cmd({type:"suggestHeldFingerPlans",request:req}),plan=result.plans[0];expect(plan.substitutions).toHaveLength(2);
 const actions=plan.substitutions.map((a:any,i:number)=>({...a,to:i?2:1}));
 await cmd({type:"acceptHeldFingerPlan",request:req,fingerprint:result.fingerprint,edits:plan.proposals.map((p:any)=>({track_id:p.track,note_index:p.index,finger:p.finger})),actions});
 const baselineSong=await cmd({type:"currentSong"});const second=baselineSong.fingerActions[1];
 const edit={contentId:song.contentId,track,index:sustained[1].index,originalTick:second.atTick,atTick:song.measures[1].startTick+Math.round(1.5*song.ppq),to:1,baseline:baselineSong.fingerActionRevision,rate:1};
 const checked=await cmd({type:"reviewHeldActionEdit",request:edit});expect(checked.valid).toBeTruthy();
 expect((await cmd({type:"currentSong"})).fingerActions).toEqual(baselineSong.fingerActions);
 expect((await raw({type:"reviewHeldActionEdit",request:{...edit,to:3}})).ok()).toBeFalsy();
 expect((await raw({type:"reviewHeldActionEdit",request:{...edit,atTick:song.measures[1].startTick+1}})).ok()).toBeFalsy();
 expect((await raw({type:"saveHeldActionEdit",request:edit,review:"unreviewed"})).ok()).toBeFalsy();
 await cmd({type:"speed",value:0.5});expect((await raw({type:"saveHeldActionEdit",request:edit,review:checked.review})).ok()).toBeFalsy();await cmd({type:"speed",value:1});
 await cmd({type:"editFingersFor",content_id:song.contentId,edits:[{track_id:track,note_index:sustained[0].index,finger:5}]});
 expect((await raw({type:"saveHeldActionEdit",request:edit,review:checked.review})).ok()).toBeFalsy();await cmd({type:"undoFingersFor",content_id:song.contentId});
 await page.goto("/");await expect(page.getByText("本地引擎已连接",{exact:true})).toBeVisible();await page.getByRole("button",{name:"乐谱",exact:true}).click();
 const label=page.locator(".score-practice-substitution");await expect(label).toHaveCount(1);await expect(label).toHaveText("3→1/3→2");
 await page.getByLabel("指法显示密度").selectOption("important");await expect(label).toHaveText("3→1/3→2");
 await label.focus();await label.press("Enter");const editor=page.getByRole("complementary",{name:"谱面指法编辑"});await expect(editor).toBeVisible();
 await editor.getByLabel("谱音演奏位置").selectOption(`${track}:${sustained[1].index}`);
 await expect(editor.getByLabel("此谱音持音换指")).toContainText("3 → 2 指");
 await editor.getByRole("button",{name:"定位换指",exact:true}).click();await expect.poll(async()=>{return (await (await request.get("http://127.0.0.1:32124/api/state")).json()).position;}).toBeCloseTo(actions[1].at,2);
 await page.screenshot({path:"../outputs/Neothesia-乐谱持音换指.png"});
 await editor.locator(".held-action-editor summary").click();await editor.getByLabel("换指拍位").fill("2.5");await editor.getByLabel("换指接替手指").selectOption("1");
 const saveEdit=editor.getByRole("button",{name:"保存换指调整",exact:true});await expect(saveEdit).toBeDisabled();
 await editor.getByRole("button",{name:"检查调整",exact:true}).click();await expect(saveEdit).toBeEnabled();
 await editor.getByLabel("换指拍位").fill("2.4");await expect(saveEdit).toBeDisabled();await editor.getByLabel("换指拍位").fill("2.5");
 await editor.getByRole("button",{name:"检查调整",exact:true}).click();await expect(saveEdit).toBeEnabled();
 await page.screenshot({path:"../outputs/Neothesia-换指拍位调整.png"});
 await page.setViewportSize({width:1000,height:900});await saveEdit.scrollIntoViewIfNeeded();await expect(saveEdit).toBeVisible();await page.screenshot({path:"../outputs/Neothesia-换指拍位调整-窄窗.png"});await page.setViewportSize({width:1440,height:960});
 await saveEdit.click();await expect(label).toHaveText("3→1");
 await expect.poll(async()=>(await cmd({type:"currentSong"})).fingerActions[1].at).toBeCloseTo(2.75,4);
 await editor.getByRole("button",{name:"撤销上一笔指法",exact:true}).click();await expect(label).toHaveText("3→1/3→2");
 await editor.getByRole("button",{name:"查看衔接音 E4",exact:true}).click();await expect(editor).toContainText("E4 · 第 2 小节");
 await label.click();await editor.getByLabel("谱音演奏位置").selectOption(`${track}:${sustained[1].index}`);
 expect((await raw({type:"clearNoteHeldFingerActions",content_id:"different",track,index:sustained[1].index})).ok()).toBeFalsy();
 await editor.getByRole("button",{name:"清除此演奏位置的换指",exact:true}).click();
 await expect.poll(async()=>(await cmd({type:"currentSong"})).fingerActions.length).toBe(1);await expect(label).toHaveText("3→1/3");
 await editor.getByRole("button",{name:"撤销上一笔指法",exact:true}).click();await expect(label).toHaveText("3→1/3→2");
 await editor.getByRole("button",{name:"5",exact:true}).click();await expect(label).toHaveAttribute("data-actions-valid","false");await expect(editor.getByLabel("此谱音持音换指")).toContainText("需要重新审阅");
 await editor.getByRole("button",{name:"撤销上一笔指法",exact:true}).click();await expect(label).toHaveAttribute("data-actions-valid","true");
 await page.getByRole("checkbox",{name:"练习指法",exact:true}).uncheck();await expect(label).toHaveCount(0);
});
