import {test,expect} from "@playwright/test";
test("快捷键编辑、冲突、重开执行与输入保护",async({page,request})=>{
 const cmd=async(data:unknown)=>{const r=await request.post("http://127.0.0.1:32124/api/command",{headers:{"X-Neothesia-Client":"web"},data});expect(r.ok(),await r.text()).toBeTruthy();return r.json()};const state=async()=> (await request.get("http://127.0.0.1:32124/api/state")).json();
 await cmd({type:"generate",spec:{tonic:0,tonality:"Major",minor_form:"Natural",pattern:"Scale",direction:"UpAndDown",hands:"Both",octaves:1,repetitions:1,tempo_bpm:120}});await cmd({type:"pause"});
 await page.goto("/");await page.getByLabel("显示与电脑键盘设置").click();const d=page.getByRole("dialog",{name:"显示与电脑键盘"}),section=d.getByRole("region",{name:"操作快捷键"});await section.getByLabel("修改快捷键：播放 / 暂停",{exact:true}).click();await page.keyboard.press("a");await expect(section.getByRole("alert")).toContainText("电脑键盘弹奏");await page.keyboard.press("Control+m");await expect(section.getByRole("alert")).toContainText("开关节拍器");await page.keyboard.press("Control+r");await expect(section.getByRole("alert")).toContainText("窗口或浏览器");await page.keyboard.press("Control+q");await expect(section.getByLabel("修改快捷键：播放 / 暂停",{exact:true})).toHaveText("Ctrl + Q");
 await section.getByLabel("修改快捷键：从头开始",{exact:true}).click();await page.keyboard.press("Escape");await expect(d).toBeVisible();await expect(section.getByLabel("修改快捷键：从头开始",{exact:true})).toHaveAttribute("aria-pressed","false");await section.scrollIntoViewIfNeeded();await page.screenshot({path:"../outputs/Neothesia-操作快捷键.png"});await page.setViewportSize({width:700,height:900});await section.scrollIntoViewIfNeeded();await page.screenshot({path:"../outputs/Neothesia-操作快捷键-窄窗.png"});await page.setViewportSize({width:1440,height:960});await d.getByRole("button",{name:"完成",exact:true}).click();
 await page.reload();await page.keyboard.press("Control+q");await expect.poll(async()=> (await state()).status).toMatch(/playing|countIn|waiting/);await page.keyboard.press("Control+q");await expect.poll(async()=> (await state()).status).toBe("paused");
 const speed=(await state()).speed;await page.keyboard.press("Control+=");await expect.poll(async()=> (await state()).speed).toBe(Math.min(2,Math.round((speed+.05)*100)/100));await page.keyboard.press("Control+-");await expect.poll(async()=> (await state()).speed).toBe(speed);
 await page.keyboard.press("Alt+ArrowRight");await expect.poll(async()=> (await state()).measure).toBe(2);await page.keyboard.press("Alt+ArrowLeft");await expect.poll(async()=> (await state()).measure).toBe(1);
 await page.keyboard.press("Alt+c");await expect.poll(async()=> (await state()).passage).not.toBeNull();await page.keyboard.press("Alt+c");await expect.poll(async()=> (await state()).passage).toBeNull();
 const baseline=(await state()).status;await page.getByLabel("显示与电脑键盘设置").click();await d.getByLabel("布局名称",{exact:true}).focus();await page.keyboard.press("Control+q");expect((await state()).status).toBe(baseline);await d.getByRole("button",{name:"完成",exact:true}).click();
 await page.locator("body").click({position:{x:3,y:3}});await page.keyboard.down("a");await expect.poll(async()=> (await state()).pressed.length).toBe(1);await page.keyboard.down("Control");await page.keyboard.up("a");await page.keyboard.up("Control");await expect.poll(async()=> (await state()).pressed.length).toBe(0);
 await page.keyboard.press("Alt+b");await expect(page.locator(".library-panel")).toHaveCount(0);await page.keyboard.press("Alt+b");await expect(page.locator(".library-panel")).toHaveCount(1);await page.keyboard.press("Control+,");await expect(d).toBeVisible();await section.getByLabel("清除快捷键：播放 / 暂停",{exact:true}).click();await expect(section.getByLabel("修改快捷键：播放 / 暂停",{exact:true})).toHaveText("未分配");await section.getByRole("button",{name:"恢复操作快捷键默认值",exact:true}).click();await expect(section.getByLabel("修改快捷键：播放 / 暂停",{exact:true})).toHaveText("空格");
 await d.getByRole("button",{name:"完成",exact:true}).click();await cmd({type:"mode",value:"recital"});const locked=(await state()).measure;await page.keyboard.press("Alt+ArrowRight");await expect(page.locator(".error-strip")).toContainText("完整演奏");expect((await state()).measure).toBe(locked);await cmd({type:"mode",value:"wait"});
});
