[package]
name = "neothesia-desktop"
version = "0.1.0"
edition.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
midi-file.workspace=true
tauri = { version = "2", features = [] }
neothesia-engine = { path = "../../neothesia-engine" }
serde_json.workspace = true
blake3.workspace = true
rfd.workspace = true

[features]
custom-protocol = ["tauri/custom-protocol"]
